// Generated by scripts/generate-post-index.mjs — do not edit by hand.
// Add or edit posts in content/posts/*.md and rebuild.

export type PostMeta = {
  slug: string;
  title: string;
  description: string;
  date: string;
  tags: string[];
  readingTime: number;
};

/**
 * The Writing section and its nav link stay hidden until this many posts are
 * published. A visibly empty blog is worse than no blog.
 */
export const REVEAL_THRESHOLD = 3;

export const posts: PostMeta[] = [];

export const blogIsLive = posts.length >= REVEAL_THRESHOLD;
