name: Continuous Deployment to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing to the gh-pages branch


    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.2'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Create a gh-pages branch and deploy the build
      - name: Deploy to GitHub Pages
        run: |
          # Check if the gh-pages branch exists remotely
          if git ls-remote --exit-code origin gh-pages >/dev/null 2>&1; then
            git push origin --delete gh-pages  
            echo "Deleted gh-pages branch" 
          else
            echo "gh-pages branch does not exist, skipping deletion" #informational message
          fi
          
          # Configure Git user
          git config user.email "tanvir.hasan.rafi.00@gmail.com" 
          git config user.name "rafi"  
      
          git checkout --orphan gh-pages 
          git rm -rf .
          
          # Add dist folder and other necessary files
          git add dist/* 

          git commit -m 'Deploy to GitHub Pages'  # Commit changes
      
      
          git push --force origin gh-pages
      


      # Step 6: (Remove this step if you configured GitHub Pages manually)
      #Optional: Configure GitHub Pages Source (for automatic setup)
      # - name: Configure GitHub Pages Source
      #   run: |
      #     curl -X POST -u "Rafi-201:${{ secrets.GITHUB_TOKEN }}" \
      #     -d '{"source": {"branch": "gh-pages", "path": "/"}}' \
      #     https://api.github.com/repos/${{ github.repository }}/pages