name: Continuous Integration

on:
  pull_request:
    branches:
      - master  # Trigger on pull requests to 'master' branch

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.2'  # Match Node.js version in package.json

      - name: Install dependencies
        run: npm install 

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules  # Cache the 'node_modules' directory
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}  # Use the hash of package-lock.json as the cache key
          restore-keys: |
            ${{ runner.os }}-node-modules-  # Fallback to previous cache keys if an exact match isn't found


      # Run ESLint on the codebase
      - name: Run ESLint
        run: |
          npm install eslint
          npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules  # Cache the 'node_modules' directory
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}  # Use the hash of package-lock.json as the cache key
          restore-keys: |
            ${{ runner.os }}-node-modules-  # Fallback to previous cache keys if an exact match isn't found


      # Build the project using Vite
      - name: Build the project
        run: npm run build
  
  merge:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == false && github.base_ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to ensure proper merging
          ref: master # explicitly check out the master branch

      - name: Set up Git
        run: |
          git config user.name "rafi"
          git config user.email "tanvir.hasan.rafi.00@gmail.com"

      - name: Merge PR into master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Ensure we're on the master branch (again for safety)
          git checkout master

          # Get the PR branch name
          PR_BRANCH=${{ github.head_ref }}

          # Check if the PR branch exists
          if ! git rev-parse --verify "origin/$PR_BRANCH" >/dev/null 2>&1; then
            echo "Error: PR branch '$PR_BRANCH' does not exist."
            exit 1
          fi

          # Merge the PR branch into master
          git merge --no-ff "origin/$PR_BRANCH" -m "Auto-merged PR #${{ github.event.pull_request.number }}"

          # Push changes to the remote repository
          git push origin master